on:
  push:
    branches:
    - main

  steps:
  - name: Check out repository
    uses: actions/checkout@v3
  - uses: actions/setup-node@v1
    with:
      node-version: '19.x'

  - name: Install dependencies and build the site
    run: |
      npm install
      npm run build

  - name: Deploy to GitHub Pages
    run: npm run deploy
